BEGIN TRANSACTION;
DROP TABLE IF EXISTS "tasks";
CREATE TABLE IF NOT EXISTS "tasks" (
	"id"	INTEGER NOT NULL UNIQUE,
	"description"	TEXT NOT NULL,
	"completed"	BOOLEAN NOT NULL DEFAULT 0,
	"deleted_at"	DATETIME,
	"created_at"	DATETIME,
	"updated_at"	TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "users";
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"email"	VARCHAR(150) NOT NULL UNIQUE,
	"password"	VARCHAR(128) NOT NULL,
	"name"	VARCHAR(150),
	"deleted_at"	DATETIME,
	"created_at"	DATETIME,
	"updated_at"	TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "cards";
CREATE TABLE IF NOT EXISTS "cards" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"slug"	TEXT,
	"resume"	TEXT NOT NULL,
	"content"	TEXT NOT NULL,
	"deleted_at"	DATETIME,
	"created_at"	DATETIME,
	"updated_at"	TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
